config/routes.rb
TestBench::Application.routes.draw do
  devise_for :users
  resources :apps
  resources :tests
  root :to => "tests#index"
end

app/models/app.rb
class App < ActiveRecord::Base
  has_many :tests, :dependent => :destroy
  belongs_to :users
end

app/models/test.rb
class Test < ActiveRecord::Base
  belongs_to :app
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :apps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :get_user
  before_action :set_app, only: [:show, :edit, :update, :destroy]

  def index
    @apps = @user.apps
  end

  def show
  end

  def new
    @app = App.new
  end

  def edit
  end

  def create
    @app = App.new(app_params)
    @user.apps << @app

    if @app.save && @user.save
      render action: 'index'
    else
      render action: 'new'
    end
  end

  def update
    @app.update(app_params)
    render action: 'index'
  end

  def destroy
    @app.destroy
    respond_to do |format|
      format.html { redirect_to apps_url }
      format.json { head :no_content }
    end
  end


  private

  def get_user
    @user = current_user
  end

  def app_params
    params.require(:app).permit(:name,:description)
  end

  def set_app
    @app = App.find(params[:id])
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :get_user
  before_action :get_apps
  before_action :set_test, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @test = Test.new
  end

  def edit
  end

  def create
    @test = Test.new(test_params)

    if @test.save
      render action: 'index'
    else
      render action: 'new'
    end
  end

  def update
    @test.update(test_params)
    render action: 'index'
  end

  def destroy
    @test.destroy
    respond_to do |format|
      format.html {redirect_to tests_url}
      format.json {head :no_content}
    end
  end

  private

  def get_user
    @user = current_user
  end

  def get_apps
    @apps = App.all
  end

  def test_params
    params.require(:test).permit(:name,:task,:status,:app_id)
  end

  def set_test
    @test = Test.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/apps/_form.html.erb
<%= form_for @app do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :description %>
	<%= f.text_field :description %>

	<%= f.submit 'Save', :class=>'button expand small' %>
<% end %>

app/views/apps/edit.html.erb
<div class="row">
	<div class="large-12 columns">
		<h1 align="center">Update Application</h1>
		<%= render 'form' %>
    <%= link_to image_tag('512/ios7-close.png', size: '40x40', alt: 'Delete Application') + 'Delete Application', @app, method: :delete, data: { confirm: 'Are you sure?' } %>
	</div>
</div>

app/views/apps/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1 align="center">My Apps</h1>

    <table align="center">
      <thead>
        <tr>
          <th width="200">Name</th>
          <th width="500">Description</th>
          <th colspan="2">Options</th>
        </tr>
      </thead>

      <tbody>
        <% @user.apps.each do |app| %>
        <tr>
          <td><%= app.name %></td>
          <td><%= app.description %></td>
          <td><%= link_to image_tag("512/ios7-gear.png", size: "30x30"), edit_app_path(app) %></td>
          <td><%= link_to image_tag("512/ios7-plus.png", size: "30x30"), new_test_path %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <p align="center">
      <%= link_to(image_tag("512/ios7-plus.png", size: "40x40", alt: "Add New Application") + "Add New Application", new_app_path) %>
    </p>
  </div>
</div>

app/views/apps/new.html.erb
<h1>New Application to Test</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %>
<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<h1>Show App</h1>

<p><strong>Name:</strong>
  <%= @app.name %>
</p>

<p><strong>Description:</strong>
  <%= @app.description %>
</p>

<%= link_to 'Edit', edit_app_path(@app) %>
<%= link_to 'Delete', @app, method: :delete, data: { confirm: 'Are you sure?'} %>
<%= link_to 'See All Applications', apps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <title><%= content_for?(:title) ? yield(:title) : "Test Bench" %></title>

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="row">
  <div class="large-12 columns">
    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1><a href="/">Test Bench</a></h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
      </ul>

      <section class="top-bar-section">
        <ul class="right">
          <% if user_signed_in? %>
              <li><%= link_to current_user.email, edit_user_registration_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
              <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %></li>
              <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link' %></li>
          <% end %>
        </ul>

        <ul class="left">
          <li><%= link_to 'My Apps', apps_path %></li>
          <li><%= link_to 'Browse Tests', tests_path %></li>
        </ul>
      </section>
    </nav>
    <% if notice %>
        <p data-alert class="alert-box success radius"><%= notice %>
          <a href="#" class="close">X</a>
        </p>
    <% end %>
    <% if alert %>
        <p data-alert class="alert-box warning radius"><%= alert %>
          <a href="#" class="close">X</a>
        </p>
    <% end %>
    <%= yield %>
</body>
</html>